services:
  - type: web
    name: lucid-core-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        value: 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

  - type: worker
    name: lucid-core-tg-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8115087412:AAG_HDvyMlU88cPoyL7Wx548esAau7UgpPw

